# Generated by Django 2.0.6 on 2018-07-15 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0002_discussion_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1500)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_app.Discussion')),
            ],
        ),
    ]
